name: Black Duck Scan 

 

on: 

  push: 

    branches: 

      - main 

  pull_request: 

    branches: 

      - main 

 

jobs: 

  blackduck-scan: 

    runs-on: ubuntu-latest 

 

    steps: 

      - name: Checkout code 

        uses: actions/checkout@v3 

 

      - name: Set up Java (Black Duck uses Java) 

        uses: actions/setup-java@v3 

        with: 

          java-version: '11' 

 

      - name: Download Synopsys Detect 

        run: | 

          curl -L -o detect.sh https://detect.synopsys.com/detect.sh 

          chmod +x detect.sh 

 

      - name: Run Black Duck scan 

        env: 

          DETECT_BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }} 

        run: | 

          ./detect.sh \ 

            --blackduck.url=https://your.blackduck.instance \ 

            --blackduck.api.token=${DETECT_BLACKDUCK_API_TOKEN} \ 

            --detect.project.name=your-project-name \ 

            --detect.project.version.name=your-version-name \ 

            --detect.tools=SIGNATURE_SCAN \ 

            --detect.blackduck.signature.scanner.snippet.mode=NONE 
